import Head from "next/head";
import Footer from "../components/footer/Footer";
import Home from "../components/home/Home";
import { useLoadingWithRefresh } from "../hooks/useLoadingWithRefresh";

export default function App() {
  const { loading } = useLoadingWithRefresh();
  return loading ? (
    "Loading.."
  ) : (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <Footer />
    </div>
  );
}
